tasks:
  - name: Sync checkout to production
    synchronize:
      src: /home/deploy/checkouts/{{ repo }}/
      dest: '{{ prod }}/{{ shorthash.stdout }}'
    delegate_to: "{{ inventory_hostname }}"
  - name: Make a directory for virtualenv
    file:
        path: "{{ deploy }}/env"
        state: directory
        mode: "u+rwx,g+rwx,o-rw"
        setype: httpd_sys_script_exec_t
  - name: Build a virtualenvironment
    command: virtualenv "{{ deploy }}/env"
  - name: Upgrade pip to latest in virtualenv
    pip:
      name: pip
      state: latest
      virtualenv: "{{ deploy }}/env"
