language: python

python:
  - "3.5"

env:
  global:
    - SOLR_VERSION=6.6.0
    - SOLR_CORE=test-derrida

addons:
  - mariadb: "5.5"

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install codecov
  - cp ci/testsettings.py derrida/local_settings.py
  - python -c "import uuid; print('SECRET_KEY = \'%s\'' % uuid.uuid4())" >> derrida/local_settings.py

before_script:
  - python manage.py build_solr_schema > solr-schema.xml
  - curl -sSL https://raw.githubusercontent.com/moliware/travis-solr/master/travis-solr.sh | SOLR_CONFS="solr-schema.xml" SOLR_VERSION=$SOLR_VERSION SOLR_CORE=$SOLR_CORE bash

script:
  - py.test --cov=derrida

after_success:
  - codecov
