# This role runs all of the tasks needed to make the new code live, starting
# with any database migrations and ending with configuring symlinks and
# restarting Apache (httpd24-httpd in Springdale)

- name: Run database migrations
  django_manage:
    command: migrate
    app_path: "{{ deploy }}"
    virtualenv: "{{ deploy }}/env"
- name: Check for current symlink as previous
  stat:
    path: "{{ install_root }}/current"
  register: previous
- name: Set current symlink
  file:
    src: "{{ deploy }}"
    dest: "{{ install_root }}/current"
  register: current
- name: If current path differs from previous current, update previous
  file:
    src: "{{ previous.lnk_target }}"
    dest: "{{ install_root }}/previous"
  when: previous.exists == True and previous.lnk_target != current_link.target
- name: If previous does not exist, create it with current
  # The logic here is that this would only occur on an initial deploy, and that
  # in the future the previous stanza will ensure the links are set correctly.
  file:
    src: "{{ deploy }}"
    dest: "{{ install_root }}/previous"
  when: previous.exists == False
- name: Set /var/www/ path to make live
  file:
    src: "{{ deploy }}"
    dest: "/var/www/{{ symlink }}"
    state: link
- name: Create courtesy symlink in /srv/www
  file:
    src: "{{ deploy }}"
    dest: "{{ install_root }}/current"
    state: link

# This makes sure that any server side settings that handle autoconfiguring
# SELinux permissions (that we would otherwise need to be root for) are
# put in place on newly created directories

# Both this and the command below it use the command/shell modules rather than
# the SELinux or Apache modules because we only have limited sudo and rights
# for both these statements
- name: Call restorecon just in case
  shell: 'restorecon -R {{ deploy }}'
  args:
    executable: /bin/bash
- name: Restart Apache (scl-httpd24-httpd)
  command: "sudo systemctl restart httpd24-httpd"
