# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 19:26
from __future__ import unicode_literals

from django.core.management import call_command
from django.contrib.auth.management import create_permissions
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'data_editor_group', app_label='common', verbose=0)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=migrations.RunPython.noop),

    ]
