# Ansible Production Deploy YAML
# --------------------
# - Variation on QA setup
# - Requires access to host via security methods (see note to CDH developers)
# - Builds repo and sets permissions
# - Does back up database
# - Does set symlinks and run migrations
# ---
#
# CDH Developers: Contact bhicks@princeton.edu or cses@princeton.edu to
# reach RC computing staff for access if necessary
#
# Usage: ansible-playbook prod_derrida-django_.yml <-e ref=hash>
#   - ref: any valid hash, tag, or branch name, default is master
# the --private-key flag can manually specify a key if you don't want to use
# ssh-add or similar, or you can add ansible_ssh_private_key_file to variables.

- hosts: '{{ group | default(qa) }}'
  remote_user: deploy
  connetion: '{{ conn }}'
  # Set environment to use scl rh-python35
  environment:
    PATH: '/opt/rh/rh-python35/root/usr/bin/:{{ lookup("env","PATH") }}'
    LD_LIBRARY_PATH: '/opt/rh/rh-python35/root/usr/lib64'
  roles:
      # Creates repo variable names and builds repo
      - projectrepo
      # Builds a production deploy and sets file permissions correctly
      - buildprod
      # Makes an emergency database backup, run migrations, and then resets
      # symlinks
      - golive
