# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 15:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_add_citationality_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='zotero_id',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('\\W', inverse_match=True, message='Zotero IDs must be alphanumeric.')]),
        ),
        migrations.AlterField(
            model_name='references',
            name='derridawork_page',
            field=models.CharField(max_length=10),
        ),
    ]
