# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.utils.text import slugify


def derridawork_slugs(apps, schema_editor):
    DerridaWork = apps.get_model('books', 'DerridaWork')
    for work in DerridaWork.objects.all():
        work.slug = slugify(work.short_title)
        work.save()


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_add_foreignkey_reference_canvas_intervention'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerridaWorkSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
                ('start_page', models.IntegerField(blank=True, null=True)),
                ('end_page', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['derridawork', 'order'],
            },
        ),
        migrations.AddField(
            model_name='derridawork',
            name='slug',
            field=models.SlugField(default='', help_text='slug for use in URLs (changing after creation will break URLs)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reference',
            name='derridawork_page',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='derridaworksection',
            name='derridawork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.DerridaWork'),
        ),
        migrations.RunPython(
            code=derridawork_slugs,
            reverse_code=migrations.RunPython.noop,
        ),

    ]
