# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_add_foreignkey_reference_canvas_intervention'),
    ]

    operations = [
        migrations.AddField(
            model_name='derridawork',
            name='abbreviation',
            field=models.SlugField(default='dg', help_text='abbreviation for use in URLs'),
            preserve_default=False,
        ),
    ]
