# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0004_intervention_add_text_translation'),
        ('books', '0003_add_m2m_canvas_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='interventions',
            field=models.ManyToManyField(blank=True, to='interventions.Intervention'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='canvases',
            field=models.ManyToManyField(blank=True, help_text="Scanned images from Derrida's Library | ", to='djiffy.Canvas'),
        ),
    ]
