# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_citationality_postmeeting_revisions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatortype',
            name='uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personbookrelationshiptype',
            name='uri',
            field=models.URLField(blank=True, null=True),
        ),
    ]
