# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_make_uri_optional_creator_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='uri',
            field=models.URLField(blank=True, null=True),
        ),
    ]
