# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_derridawork_section_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='copy',
            field=models.CharField(blank=True, help_text='Label to distinguish multiple copies of the same edition', max_length=3, null=True),
        ),
    ]
