# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_derridawork_abbreviation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
                ('start_page', models.IntegerField(blank=True, null=True)),
                ('end_page', models.IntegerField(blank=True, null=True)),
                ('derridawork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.DerridaWork')),
            ],
            options={
                'ordering': ['derridawork', 'order'],
            },
        ),
        migrations.AlterField(
            model_name='reference',
            name='derridawork_page',
            field=models.IntegerField(),
        ),
    ]
