# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 13:24
from __future__ import unicode_literals

from django.core.management import call_command
from django.contrib.auth.management import create_permissions
from django.db import migrations

def load_fixture(apps, schema_editor):
    call_command('loaddata', 'initial_languages', app_label='books', verbose=0)



class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_optional_uri_fields_language_subject'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=migrations.RunPython.noop),
    ]
