# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djiffy', '0002_view_permissions'),
        ('books', '0005_add_slugs_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='suppress_all_images',
            field=models.BooleanField(default=False, help_text='Suppress large image display for all annotated pages\n        in this volume, to comply with copyright take-down requests.\n        (Overview images, insertions, and thumbnails will still display.)'),
        ),
        migrations.AddField(
            model_name='instance',
            name='suppressed_images',
            field=models.ManyToManyField(blank=True, help_text='Suppress large image for specific annotated images to comply\n        with copyright take-down requests.', to='djiffy.Canvas'),
        ),
    ]
