# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_initial_languages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='References',
            new_name='Reference',
        ),
        migrations.RenameModel(
            old_name='ReferenceTypes',
            new_name='ReferenceType',
        ),
    ]
