# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_fix_pluralizatition_citationality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencetype',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='referencetype',
            name='name',
            field=models.CharField(default='No type', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
