# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_add_str_referencetype_derridawork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencetype',
            name='type',
        ),
    ]
