# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_initial_reftypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='book_page',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='reference_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='books.ReferenceType'),
            preserve_default=False,
        ),
    ]
