# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_add_uri_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='end_year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='start_year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personbook',
            name='end_year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personbook',
            name='start_year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
