# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_add_page_range'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='journal_id',
            new_name='journal',
        ),
    ]
