# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 18:36
from __future__ import unicode_literals

from django.core.management import call_command
from django.contrib.auth.management import create_permissions
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'initial_itemtypes', app_label='books', verbose=0)


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_rename_journal_id_journal'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=migrations.RunPython.noop),

    ]
