# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_add_initial_item_types'),
    ]

    operations = [
    ]
