# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_add_initial_item_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(blank=True, help_text='Date in YYYY-MM-DD format. If either pub_month or pub_day are missing, will autoset to 01 to indicate this on save.', null=True, verbose_name='Publication/Print Date'),
        ),
    ]
