# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_help_text_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='book_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
