# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_raise_char_limit_book_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['primary_title'], 'verbose_name': 'Derrida library work', 'verbose_name_plural': 'Derrida library works'},
        ),
        migrations.AlterField(
            model_name='book',
            name='larger_work_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(blank=True, help_text='Date in YYYY-MM-DD format. If either pub_month or pub_day_missing are checked 01 for MM or DD indicates that the information is not known.', null=True, verbose_name='Publication/Print Date'),
        ),
    ]
