# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_expand_larger_title_space_improve_admin_clarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='call_number',
            field=models.CharField(blank=True, help_text='Used for Derrida shelf mark', max_length=255, null=True),
        ),
    ]
