# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0025_help_text_catatalogue'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatedBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_symmetrical', models.BooleanField(default=True)),
                ('from_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_book', to='books.Book')),
                ('to_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_book', to='books.Book')),
            ],
            options={
                'verbose_name': 'Associated Book',
                'verbose_name_plural': 'Associated Books',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='books',
            field=models.ManyToManyField(through='books.AssociatedBook', to='books.Book'),
        ),
    ]
