# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0026_book_many_to_many_self'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associatedbook',
            name='is_symmetrical',
        ),
    ]
