# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0027_remove_symmetrical_flag_associated_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerridaWorkBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Edition - Derrida work relations',
                'verbose_name': 'Edition - Derrida work relation',
            },
        ),
        migrations.AddField(
            model_name='associatedbook',
            name='is_collection',
            field=models.BooleanField(default=False, help_text='Denotes that a BookSection/Book or other section/work relationship is an actual parent-child. Assumes parent is larger work even though relationship is symmetric.'),
        ),
        migrations.AlterField(
            model_name='associatedbook',
            name='to_book',
            field=models.ForeignKey(help_text='Creates associations between works. To edit an existing instance, please delete the relationship and make a new one', on_delete=django.db.models.deletion.CASCADE, related_name='to_book', to='books.Book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='original_pub_info',
            field=models.TextField(blank=True, null=True, verbose_name='Original Publication Information'),
        ),
        migrations.AddField(
            model_name='derridaworkbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book', verbose_name='Cited edition'),
        ),
        migrations.AddField(
            model_name='derridaworkbook',
            name='derridawork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.DerridaWork', verbose_name='Cited in'),
        ),
        migrations.AddField(
            model_name='derridawork',
            name='cited_books',
            field=models.ManyToManyField(help_text='Indicate which edition(s) of a book Derrida cites in this work.', through='books.DerridaWorkBook', to='books.Book'),
        ),
    ]
