# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0027_remove_symmetrical_flag_associated_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerridaWorkBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_edition', to='books.Book')),
                ('derridawork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_work', to='books.DerridaWork')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='associatedbook',
            name='to_book',
            field=models.ForeignKey(help_text='Creates associations between works. To edit an existing instance, please delete the relationship and make a new one', on_delete=django.db.models.deletion.CASCADE, related_name='to_book', to='books.Book'),
        ),
        migrations.AddField(
            model_name='derridawork',
            name='cited_books',
            field=models.ManyToManyField(help_text='Indicate which edition(s) of a book Derrida cites in this work.', related_name='book_edition', to='books.DerridaWorkBook'),
        ),
    ]
