# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0028_add_derrida_workbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='anchor_text',
            field=models.TextField(blank=True),
        ),
    ]
