# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0029_tidy_book_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='associatedbook',
            name='is_collection',
            field=models.BooleanField(default=False, help_text='Denotes that a BookSection/Book or other section/work relationship is an actual parent-child. Assumes parent is larger work even though relationship is symmetric.'),
        ),
    ]
