# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0031_migrate_books_to_works_instances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='cited_in',
            field=models.ManyToManyField(blank=True, help_text='Derrida works that cite this edition or instance', to='books.DerridaWork'),
        ),
        migrations.AlterField(
            model_name='worksubject',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
