# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0032_cited_in_optional_subject_default_not_primary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associatedbook',
            name='from_book',
        ),
        migrations.RemoveField(
            model_name='associatedbook',
            name='to_book',
        ),
        migrations.RemoveField(
            model_name='book',
            name='books',
        ),
        migrations.RemoveField(
            model_name='book',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='book',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='book',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='book',
            name='owning_institutions',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pub_place',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='book',
            name='subjects',
        ),
        migrations.AlterUniqueTogether(
            name='booklanguage',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='booklanguage',
            name='book',
        ),
        migrations.RemoveField(
            model_name='booklanguage',
            name='language',
        ),
        migrations.AlterUniqueTogether(
            name='booksubject',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='booksubject',
            name='book',
        ),
        migrations.RemoveField(
            model_name='booksubject',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='catalogue',
            name='book',
        ),
        migrations.RemoveField(
            model_name='catalogue',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='book',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='creator_type',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='person',
        ),
        migrations.RemoveField(
            model_name='derridaworkbook',
            name='book',
        ),
        migrations.RemoveField(
            model_name='derridaworkbook',
            name='derridawork',
        ),
        migrations.RemoveField(
            model_name='derridawork',
            name='cited_books',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='book',
        ),
        migrations.AlterField(
            model_name='instance',
            name='print_date',
            field=models.DateField(blank=True, help_text='Date as YYYY-MM-DD, YYYY-MM, or YYYY format. Use print date day/month/year known flags to indicate that the information is not known.', null=True, verbose_name='Print Date'),
        ),
        migrations.AlterField(
            model_name='work',
            name='year',
            field=models.IntegerField(blank=True, help_text='Original publication date', null=True),
        ),
        migrations.DeleteModel(
            name='AssociatedBook',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookLanguage',
        ),
        migrations.DeleteModel(
            name='BookSubject',
        ),
        migrations.DeleteModel(
            name='Catalogue',
        ),
        migrations.DeleteModel(
            name='Creator',
        ),
        migrations.DeleteModel(
            name='DerridaWorkBook',
        ),
        migrations.DeleteModel(
            name='ItemType',
        ),
    ]
