# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 19:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djiffy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True)),
                ('quote', models.TextField(blank=True)),
                ('uri', models.URLField()),
                ('extra_data', jsonfield.fields.JSONField(default='{}')),
                ('intervention_type', models.CharField(choices=[('A', 'Annotation'), ('I', 'Insertion')], default='A', max_length=2)),
                ('canvas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djiffy.Canvas')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'permissions': (('view_annotation', 'View annotation'), ('admin_annotation', 'Manage annotation')),
            },
        ),
    ]
