# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_instance_digital_edition'),
        ('interventions', '0002_add_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='quote_language',
            field=models.ForeignKey(blank=True, help_text='Language of the anchor text', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='books.Language'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='text_language',
            field=models.ForeignKey(blank=True, help_text='Language of the annotation text', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='books.Language'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags to describe this intervation and its characteristics', to='interventions.Tag'),
        ),
    ]
