# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0003_add_intervention_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='text_translation',
            field=models.TextField(blank=True, help_text='Translation of the intervention text (optional)'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='text_language',
            field=models.ForeignKey(blank=True, help_text='Language of the intervention text', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='books.Language'),
        ),
    ]
