# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0004_intervention_add_text_translation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intervention',
            options={'permissions': (('view_intervention', 'View intervention'),)},
        ),
    ]
