- name: Clone the repo if doesn't already exist and make sure it's on gitref
  git:
    repo: '{{ repo_url }}'
    dest: '{{ clone_root }}'
    version: '{{ gitref }}'
  register: repo_info
- name: Get version information
  command: 'printf "%s\n" "import {{ djangoapp }}" "print {{ djangoapp }}".__version__ | python -'
  args:
    chdir: {{ clone_root }}
  # used to generate the {{ version }} variable
  register: ver
  check_mode: no
- name: Sync checkout to production
  synchronize:
    src: /home/deploy/checkouts/{{ repo }}/
    dest: '{{ deploy }}'
  delegate_to: '{{ inventory_hostname }}'
