# This role serves to configure the settings repo (if it does not already
# exist on the deploy server), then clone the github repoistory for the project
# to the remote server for deployment
- name: Clone settings repository locally
  git:
      repo: 'git@github.com:Princeton-CDH/deployment.git'
      # Use lookup here because we're working on the machine running ansible
      dest: "{{ lookup('env', 'HOME') }}/.deploy/"
      version: 'master'
  delegate_to: localhost
- name: Clone the repo if doesn't already exist and make sure it's on gitref
  git:
    repo: '{{ repo_url }}/'
    dest: '{{ clone_root }}/{{ repo }}'
    version: '{{ gitref }}'
  register: repo_info
- name: Get version information
  script: get_ver.py {{ clone_root}}/{{ repo }} {{ djangoapp }}
  register: ver
  check_mode: no
- name: Sync checkout to deploy directory
  synchronize:
    src: '{{ clone_root }}/{{ repo }}/'
    dest: '{{ deploy }}'
  delegate_to: '{{ inventory_hostname }}'
