name: unit tests

on:
  push: # run on every push or PR to any branch
  pull_request:

env:
  SOLR_VERSION: 6.6.5
  SOLR_CORE: test-derrida
  # JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64

jobs:
  python-unit:
    name: python unit tests
    runs-on: ubuntu-latest

    services:
      db:
        image: mariadb
        env:
          MYSQL_DATABASE: derrida
          MYSQL_ROOT_PASSWORD: derrida
        ports:
          - 3306:3306
      solr:
        image: solr:6.6
        ports:
          - 8983:8983
    steps:
      - uses: actions/checkout@v2
      - run: docker cp solr_conf ${{ job.services.solr.id }}:/opt/solr/server/solr/configsets/derrida
      - run: docker exec --user root ${{ job.services.solr.id }} /bin/bash -c "chown -R solr:solr /opt/solr/server/solr/configsets/derrida"
      - uses: actions/setup-python@v2
        with:
          # This version is necessary for CI to run, despite the site being on python 3.5
          python-version: 3.7.6

      # Perform installations
      - run: pip install -r requirements.txt
      - run: pip install codecov
      - run: cp ci/testsettings.py derrida/local_settings.py
      - run: python -c "import uuid; print('SECRET_KEY = \'%s\'' % uuid.uuid4())" >> derrida/local_settings.py
      - run: npm ci
      # - run: SOLR_VERSION=$SOLR_VERSION SOLR_CORE=$SOLR_CORE bash ci/config_solr.sh

      # Configure site
      - run: python manage.py build_solr_schema --configure-directory=downloads/solr-$SOLR_VERSION/server/solr/$SOLR_CORE/conf --reload-core $SOLR_CORE
      - run: python manage.py migrate
      - run: python manage.py loaddata sample_work_data test_references
      - run: python manage.py rebuild_index --noinput # index in solr
      - run: python manage.py runserver --insecure & # run for pa11y, serve static content

      # Perform test
      - run: py.test --cov=derrida
