name: unit tests

on:
  push: # run on every push or PR to any branch
  # pull_request:

env:
  SOLR_CORE: derrida

jobs:
  python-unit:
    name: python unit tests
    runs-on: ubuntu-latest

    services:
      db:
        image: mariadb
        env:
          MYSQL_DATABASE: derrida
          MYSQL_ROOT_PASSWORD: derrida
        ports:
          - 3306:3306
      solr:
        image: solr:6.6
        ports:
          - 8983:8983
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          # This version is necessary for CI to run, despite the site being on python 3.5
          python-version: 3.7.6
      - uses: actions/setup-node@v2
        with:
          node-version: 8.16

      # Perform installations
      - run: pip install -r ci/ci-requirements.lock
      - run: npm ci
      # - run: pip install codecov

      # Setup local settings
      - run: cp ci/testsettings.py derrida/local_settings.py
      - run: python -c "import uuid; print('SECRET_KEY = \'%s\'' % uuid.uuid4())" >> derrida/local_settings.py

      # configure solr
      - name: Create solr core
        run: docker exec --user root ${{ job.services.solr.id }} /bin/bash -c "chown -R solr:solr /opt/solr/"
      - run: docker exec --user solr ${{ job.services.solr.id }} /bin/bash -c "/opt/solr/bin/solr create -c $SOLR_CORE -n basic_configs"

      # Configure site
      # - name: Copy solr config
      #   run: docker cp ${{ job.services.solr.id }}:/opt/solr/server/solr/$SOLR_CORE/conf tmp-solr-config
      # - name: run build_solr_schema to local schema
      #   run: python manage.py build_solr_schema --configure-directory=tmp-solr-config
      # - name: upload configured schema
      #   run: docker cp tmp-solr-config ${{ job.services.solr.id }}:/opt/solr/server/solr/$SOLR_CORE/conf
      - name: restart solr
        run: docker exec --user solr ${{ job.services.solr.id }} /bin/bash -c "/opt/solr/bin/solr restart"

      - run: python manage.py migrate
      - run: python manage.py loaddata sample_work_data test_references
      - run: python manage.py rebuild_index --noinput # index in solr
      - run: python manage.py runserver --insecure & # run for pa11y, serve static content

      # Perform test
      - run: python -m pytest
      # - run: py.test --cov=derrida
